name: Install Metacall on Linux Test

on: [push, pull_request, workflow_dispatch]

jobs:
  install-local:
    name: Install Metacall via Default Installation (local)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: ./test.sh

  install-remote:
    name: Install Metacall via Default Installation (remote)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - run: echo "METACALL_INSTALL_CERTS=certificates_remote" >> $GITHUB_ENV
      - name: Tests
        run: ./test.sh
